version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    # command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
